/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.penggajian.karyawan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class inputdata extends javax.swing.JFrame {
    private String nama;
    private String lembur;
    private String jabatan;
    private String pendidikan;
    private String bersih;
    

    /**
     * Creates new form inputdata
     */
    public inputdata() {
        initComponents();
        buttonGroup2.add(rbtnmanager);
        buttonGroup2.add(rbtnkaryawan);
        buttonGroup3.add(rbtnsma);
        buttonGroup3.add(rbtnd3);
        buttonGroup3.add(rbtns1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        txgaji = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txlembur = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        rbtnmanager = new javax.swing.JRadioButton();
        rbtnkaryawan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbtnsma = new javax.swing.JRadioButton();
        rbtnd3 = new javax.swing.JRadioButton();
        rbtns1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txhlembur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txpajak = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txbersih = new javax.swing.JTextField();
        btnsimpan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 214, 229));

        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Input Data Karyawan");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Gaji");

        jLabel5.setText("Lembur");

        btnhitung.setBackground(new java.awt.Color(200, 214, 229));
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(200, 214, 229));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        rbtnmanager.setBackground(new java.awt.Color(200, 214, 229));
        rbtnmanager.setText("Manager");
        rbtnmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmanagerActionPerformed(evt);
            }
        });

        rbtnkaryawan.setBackground(new java.awt.Color(200, 214, 229));
        rbtnkaryawan.setText("Karyawan");
        rbtnkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnkaryawanActionPerformed(evt);
            }
        });

        jLabel6.setText("Pendidikan");

        rbtnsma.setBackground(new java.awt.Color(200, 214, 229));
        rbtnsma.setText("SMA");
        rbtnsma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnsmaActionPerformed(evt);
            }
        });

        rbtnd3.setBackground(new java.awt.Color(200, 214, 229));
        rbtnd3.setText("D3");

        rbtns1.setBackground(new java.awt.Color(200, 214, 229));
        rbtns1.setText("S1");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txhlembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txhlemburActionPerformed(evt);
            }
        });

        jLabel7.setText("Pajak");

        txpajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpajakActionPerformed(evt);
            }
        });

        jLabel8.setText("Gaji Bersih");

        btnsimpan1.setBackground(new java.awt.Color(200, 214, 229));
        btnsimpan1.setText("Simpan");
        btnsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txgaji, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txnama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txpajak)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnmanager)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnkaryawan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txlembur)
                                    .addComponent(rbtnsma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnd3)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtns1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txhlembur, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                            .addComponent(txbersih)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnhitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsimpan1)
                        .addGap(7, 7, 7)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtnmanager)
                    .addComponent(rbtnkaryawan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnsma)
                    .addComponent(rbtnd3)
                    .addComponent(rbtns1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txlembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(txhlembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txpajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txbersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhitung)
                    .addComponent(btnreset)
                    .addComponent(btnsimpan1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmanagerActionPerformed
        // TODO add your handling code here:
         txgaji.setText("5000000");
    }//GEN-LAST:event_rbtnmanagerActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        if(txnama.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        }
        else if (rbtnmanager.isSelected() == false && rbtnkaryawan.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null, "Pilih salah satu dari jabatan");
        }
        else if(rbtnsma.isSelected() == false && rbtnd3.isSelected() == false && rbtns1.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null, "Pilih salah satu dari pendidikan");
        }
        else if (txlembur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah lembur");
        }
        else if (txhlembur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "tekan tombol hitung jumlah lembur");
        }
        else
        {
            //fungsi tombol hitung
            int gaji = Integer.parseInt(txgaji.getText());
            int hlembur = Integer.parseInt(txhlembur.getText());
            
            int total = gaji + hlembur;
            int pajak = (int) (0.1 * total);
            txpajak.setText("" + pajak);
            int bersih = gaji + hlembur - pajak;
            txbersih.setText("" + bersih);
            
        }        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void rbtnsmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnsmaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rbtnsmaActionPerformed

    private void rbtnkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnkaryawanActionPerformed
        // TODO add your handling code here:
            txgaji.setText("2000000");     
    }//GEN-LAST:event_rbtnkaryawanActionPerformed

    private void txhlemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhlemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhlemburActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if(rbtnsma.isSelected() == true)
       {
           int lb = Integer.parseInt(txlembur.getText());
           int hs = lb*50000;
           txhlembur.setText(""+hs);
       }
       if (rbtnd3.isSelected() == true)
       {
           int lb = Integer.parseInt(txlembur.getText());
           int hs = lb*75000;
           txhlembur.setText(""+hs);
       }
       if (rbtns1.isSelected() == true)
       {
           int lb = Integer.parseInt(txlembur.getText());
           int hs = lb*100000;
           txhlembur.setText(""+hs);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txpajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpajakActionPerformed
        // TODO add your handling code here:
        int gaji = Integer.parseInt(txgaji.getText());
        int hlembur = Integer.parseInt(txhlembur.getText());
        int pajak = Integer.parseInt(txpajak.getText());
        int bersih = Integer.parseInt(txbersih.getText());
        pajak = (10/100)*gaji;
    }//GEN-LAST:event_txpajakActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txnama.setText("");
        txlembur.setText("");
        txhlembur.setText("");
        txgaji.setText("");
        txpajak.setText("");
        txbersih.setText("");
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_btnresetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fmawal c = new fmawal();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan1ActionPerformed
        if(txnama.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        }
        else if (rbtnmanager.isSelected() == false && rbtnkaryawan.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null, "Pilih salah satu dari jabatan");
        }
        else if(rbtnsma.isSelected() == false && rbtnd3.isSelected() == false && rbtns1.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null, "Pilih salah satu dari pendidikan");
        }
        else if (txlembur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah lembur");
        }
        else if (txhlembur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "tekan tombol hitung jumlah lembur");
        }
        else
        {
        nama = txnama.getText().toString().trim();
        lembur = txlembur.getText().toString().trim();
        bersih = txbersih.getText().toString().trim();
        if(rbtnsma.isSelected() == true)
       {
           pendidikan = "SMA";
       }
        else if (rbtnd3.isSelected() == true)
       {
            pendidikan = "D3";
       }
        else if (rbtns1.isSelected() == true)
       {
            pendidikan = "S1";
       }
       if (rbtnmanager.isSelected() == true)
       {
           jabatan = "MANAGER";
       }
       else{
           jabatan = "KARYAWAN";
       }
       try{
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO tbdata VALUES (?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nama);
                p.setString(2, jabatan);
                p.setString(3, pendidikan);
                p.setString(4, lembur);
                p.setString(5, bersih);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null,"Data berhasil kesimpan");
                
            }catch (SQLException e)
            {
                System.out.println("error");
            }finally{
                this.dispose();
                fmawal a = new fmawal();
                a.setVisible(true);
            }
    }//GEN-LAST:event_btnsimpan1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnd3;
    private javax.swing.JRadioButton rbtnkaryawan;
    private javax.swing.JRadioButton rbtnmanager;
    private javax.swing.JRadioButton rbtns1;
    private javax.swing.JRadioButton rbtnsma;
    private javax.swing.JTextField txbersih;
    private javax.swing.JTextField txgaji;
    private javax.swing.JTextField txhlembur;
    private javax.swing.JTextField txlembur;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txpajak;
    // End of variables declaration//GEN-END:variables
}
